language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libusb-1.0-0-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
