language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libusb-1.0-0-dev

before_script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=$(pwd)/../install ..

script:
  - make
  - make install
  - make package

