# - Try to find getopt library (for Windows)
# Once done this will define
#
# GETOPT_FOUND - system has getopt
# GETOPT_INCLUDE_DIRS - the getopt include directory
# GETOPT_LIBRARIES - Link these to use getopt
# GETOPT_DEFINITIONS - Compiler switches required for using getopt
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

find_path(GETOPT_INCLUDE_DIR
	NAMES
		getopt.h
	PATHS
		/usr/include
		/usr/local/include
		/sw/include
)

find_library(GETOPT_LIBRARY
	NAMES
		getopt
	PATHS
		/usr/lib
		/usr/local/lib
		/sw/lib
)

include(FindPackageHandleStandardArgs)

# handle the QUIETLY and REQUIRED arguments and set GETOPT_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(GetOpt DEFAULT_MSG
								  GETOPT_LIBRARY GETOPT_INCLUDE_DIR)

# show the variables only in the advanced view
mark_as_advanced(GETOPT_INCLUDE_DIR GETOPT_LIBRARY)

set(GETOPT_INCLUDE_DIRS
	${GETOPT_INCLUDE_DIR}
)
set(GETOPT_LIBRARIES
	${GETOPT_LIBRARY}
)
